### ISSUE TITLE
CaseServerDataSource

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-case-server#18]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Connection between REST API and IIDM data source is not easy. 

* **What is the expected behavior?**
We have to implement a `CaseServerDataSource':

```java
class CaseServerDataSource implement ReadOnlyDataSource {

    public CaseServerDataSource(RestTemplate restTemplate) {
    }
...
}
```

That will connect to case server REST API to get data streams. Following new methods have to be implemented.

```http
/cases/:caseName?fileName=
/cases/:caseName?suffix=&ext=
/cases/:caseName/exists?fileName=
/cases/:caseName/exists?suffix=&ext=
```

We also to have to pay attention in the implementation so that data is streams from end to end (from file on case server side, to importer that uses the data source).
Also byte stream in the REST API could be compressed (could be done later on).

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by jonenst** [comment]
Instead of RestTemplate, we should aim for spring-webflux Webclient

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html
> NOTE: As of 5.0, the non-blocking, reactive org.springframework.web.reactive.client.WebClient offers a modern alternative to the RestTemplate with efficient support for both sync and async, as well as streaming scenarios. The RestTemplate will be deprecated in a future version and will not have major new features added going forward. See the WebClient section of the Spring Framework reference documentation for more details and example code.
